---
# Start this docker compose file with:
#
# $ docker compose up test
#
# Start the dev env with:
#
# $ docker compose up -d dev
#
services:
  dev:
    # node:24-alpine
    image: docker.io/library/node@sha256:e67514e5d0f6c46656005e1b693b2ec9d52e80b641307de684d4a015ba7a4eaf
    volumes:
    - ./:/code
    user: "1000:1000"
    command:
    - infinity
    entrypoint:
    - sleep
    - infinity
