import { createEditorPane, createTurtlePane, applyEditorFontSize } from './editor/editorPane.js';
import { createDocumentModel } from './rdf/documentModel.js';
import { renderMermaidPreview } from './mermaidPreview/previewPane.js';
import { mountGraphView } from './viz/mountGraphView.js';
import { mountQueryView } from './query/mountQueryView.js';
import { placeUnderAnchor } from './viz/filterChip.js';
import { renderDiagramList } from './viz/diagramList.js';
import { createColumnLayout } from './layout/columns.js';
import { wireCopyButton } from './clipboard.js';
import {
  currentFile,
  deleteFile,
  duplicateFile,
  fileById,
  importFile,
  isDirty,
  openFile,
  openScratch,
  renameFile,
  saveAs,
  saveOver,
  setWorkingContent,
  sortedFiles,
  uniqueName,
} from './files/fileStore.js';
import {
  clearStore,
  flushStore,
  loadStore,
  onStorageError,
  saveStore,
  saveWorking,
} from './files/filesPersist.js';
import { renderFilesPane } from './files/filesPane.js';
import { downloadText, pickTextFile } from './files/fileTransfer.js';
import { createQueryClient } from './query/queryClient.js';
import { clearQueries } from './query/queryPersist.js';
import { buildSessionDump, dumpFileName } from './query/sessionDump.js';
import wellKnownAuthFlows from './data/enrichment/well-known-auth-flows.ttl?raw';
// The D3FEND release, generated by app/scripts/rebuild-data.sh from the same
// D3FEND_VERSION that downloads the ontology and rebuilds every projection under
// src/data/ (app/config/README.md). Imported rather than written into index.html so
// the header cannot drift from the data the app answers with.
import d3fendConfig from '../config/d3fend.json';

// The graph and SPARQL views are mounted units shared with the VS Code extension
// (docs/adr/0043-vscode-extension.md); what is left here is the SPA's own shell: the
// CodeMirror panes, the browser file store, the column layout and the session buttons.

const DEFAULT_DIAGRAM_ID = 'current';

// `testcase*.md` states the supported syntax and the quads it must produce —
// a specification the test suite reads off disk, not a diagram to open. The
// picker offers examples only (ADR 0010), so the negation lives here beside
// the pattern that would otherwise pick them up.
const exampleModules = import.meta.glob(['./data/examples/*.md', '!./data/examples/testcase*.md'], {
  query: '?raw',
  import: 'default',
  eager: true,
});
const examples = Object.keys(exampleModules)
  .sort()
  .map((path) => {
    const content = exampleModules[path];
    // The dropdown lists files, so the entry is the file name. A document holds
    // several diagrams, and the first one's `title:` frontmatter does not name
    // the file — it only gets to be the tooltip.
    const titleMatch = /^title:\s*(.+)$/m.exec(content);
    const fileName = path.split('/').pop();
    return { name: fileName.replace(/\.md$/, ''), fileName, title: titleMatch?.[1].trim() ?? '', content };
  });

const editorHost = document.getElementById('editor-host');
const mermaidHost = document.getElementById('mermaid-host');
const diagramListHost = document.getElementById('diagram-list-host');
const turtleHost = document.getElementById('turtle-host');
const turtleDirtyBadge = document.getElementById('turtle-dirty');
const regenerateTurtleButton = document.getElementById('regenerate-turtle-button');
const filesHost = document.getElementById('files-host');
const filesDirtyBadge = document.getElementById('files-dirty');
const fileSaveAsButton = document.getElementById('file-save-as-button');
const fileImportButton = document.getElementById('file-import-button');
const fileExportButton = document.getElementById('file-export-button');
const fileImportInput = document.getElementById('file-import-input');
const lintChip = document.getElementById('lint-chip');
const lintChipLabel = document.getElementById('lint-chip-label');
const lintPanel = document.getElementById('lint-panel');
const copyEditorButton = document.getElementById('copy-editor-button');
const copyTurtleButton = document.getElementById('copy-turtle-button');
const dumpSessionButton = document.getElementById('dump-session-button');
const destroySessionButton = document.getElementById('destroy-session-button');

const d3fendVersionLink = document.getElementById('d3fend-version');
d3fendVersionLink.textContent = `D3FEND ${d3fendConfig.version}`;
d3fendVersionLink.href = d3fendConfig.homepage;
const released = d3fendConfig.releaseDate ? `, released ${d3fendConfig.releaseDate}` : '';
d3fendVersionLink.title =
  `Built against D3FEND ${d3fendConfig.version}${released} — the ontology behind ` +
  'completion, node colour and every query answer';

/**
 * Reports lint messages on the header chip, which opens the full list in its
 * popover. Takes one message or a list of them: the count is what a chip narrow
 * enough to never cover a pane control can still say honestly.
 */
function showLint(message) {
  const messages = (Array.isArray(message) ? message : [message]).filter(Boolean);
  if (!messages.length) {
    lintChip.hidden = true;
    lintPanel.hidePopover();
    return;
  }
  lintChipLabel.textContent =
    messages.length > 1 ? `${messages.length} issues` : messages[0];
  lintChip.title = messages.join('\n');
  lintChip.hidden = false;
  lintPanel.replaceChildren(
    ...messages.map((text) => {
      const p = document.createElement('p');
      p.textContent = text;
      return p;
    }),
  );
  // Re-place it: a list that grew while it was open no longer fits where it did.
  if (lintPanel.matches(':popover-open')) placeUnderAnchor(lintChip, lintPanel);
}

lintPanel.addEventListener('beforetoggle', (event) => {
  if (event.newState === 'open') lintPanel.style.visibility = 'hidden';
});
lintPanel.addEventListener('toggle', (event) => {
  const isOpen = event.newState === 'open';
  lintChip.setAttribute('aria-expanded', String(isOpen));
  if (isOpen) placeUnderAnchor(lintChip, lintPanel);
});
window.addEventListener('resize', () => {
  if (lintPanel.matches(':popover-open')) placeUnderAnchor(lintChip, lintPanel);
});

const doc = createDocumentModel({
  enrichmentTurtle: wellKnownAuthFlows,
  defaultDiagramId: DEFAULT_DIAGRAM_ID,
});
let diagrams = [];
let selectedHash = null;
// Set once the TriG pane has been hand-edited: from then on mermaid edits still
// drive the graph, but they stop rewriting the pane behind the user's back.
let turtleDirty = false;

const TURTLE_EDITED_NOTE = ' — the TriG pane is edited, press Regenerate to see it';

// The graph view reads the document through `setDocument` and reports what the user
// asked for through these callbacks. `editorPane`, `turtlePane`, `queryView` and
// `dock` are declared below: every callback runs after they exist, since the first
// one fires from the editor's own first onChange.
const graphView = mountGraphView(document.getElementById('graph-pane'), {
  isActive: () => dock.isVisible('graph'),
  prompt: (message, value) => Promise.resolve(window.prompt(message, value)),
  knownGraphNames: () => doc.knownGraphNames(),
  source: {
    has: (mermaidId) => editorPane.hasSource(mermaidId),
    reveal: (mermaidId) => editorPane.revealSource(mermaidId),
    hasEdge: (keys) => editorPane.hasEdgeSource(keys),
    revealEdge: (keys) => editorPane.revealEdgeSource(keys),
    addRelation: (mermaidId, rel) => editorPane.addRelation(mermaidId, rel),
    changeClass: (mermaidId, oldQname, newQname) =>
      editorPane.changeNodeClass(mermaidId, oldQname, newQname),
  },
  onAddGraph: async (contribution) => {
    doc.add(contribution);
    if (!turtleDirty) await renderTurtle();
    return turtleDirty ? TURTLE_EDITED_NOTE : undefined;
  },
  onRemoveGraph: async (name) => {
    doc.remove(name);
    if (!turtleDirty) await renderTurtle();
  },
  // The Sources popover lists the document graphs that are in query scope, so it
  // goes stale on the same events the Graphs one does. The engine is *not* synced
  // here: that happens on Run (docs/adr/0020-sparql-query-engine.md).
  onApplied: () => queryView.renderSources(),
  onQueryNode: (iri) => {
    dock.revealView('query');
    queryView.queryNode(iri);
  },
  onQueryClassPair: (pair) => {
    dock.revealView('query');
    queryView.queryClassPair(pair);
  },
  onPrefsChange: (next) => {
    applyEditorFontSize(next.editorFontSize);
    // CodeMirror caches character metrics: without this the new size wraps and
    // places the caret against the old one until something else forces a measure.
    editorPane.requestMeasure();
    turtlePane.requestMeasure();
    queryView.requestMeasure();
  },
});
// The editors are sized by CSS, so this runs before they are built and their first
// measurement already reads the saved size.
applyEditorFontSize(graphView.prefs().editorFontSize);

const queryView = mountQueryView(document.getElementById('query-pane'), {
  isActive: () => dock.isVisible('query'),
  prompt: (message, value) => Promise.resolve(window.prompt(message, value)),
  confirm: (message) => Promise.resolve(window.confirm(message)),
  createEngine: createQueryClient,
  contributions: () => doc.contributions(),
  selectedNode: () => {
    const selection = graphView.selection();
    return selection?.kind === 'node' ? selection.id : null;
  },
  drawnNodeIds: () => graphView.drawnNodeIds(),
  onReveal: (iri) => {
    dock.revealView('graph');
    // After the reveal: cytoscape cannot centre on a node in a hidden container.
    if (!graphView.selectNode(iri)) {
      graphView.flashError('That node is hidden by a filter or folded away');
    }
  },
  onAddGraph: async (contribution) => {
    doc.add(contribution, { sweepable: true });
    await graphView.addContribution(contribution, { save: true });
    if (!turtleDirty) await renderTurtle();
    dock.revealView('graph');
  },
  onLint: showLint,
});

/**
 * Serializes every contribution into the TriG pane — the whole document, not what
 * is drawn, since the Graphs chip filters the view and not the data.
 */
async function renderTurtle() {
  turtlePane.setText(await doc.toTrig(), { silent: true });
}

/** Hand-edited TriG is never overwritten silently; the badge is the reconciliation cue. */
function setTurtleDirty(dirty, label = 'edited') {
  turtleDirty = dirty;
  turtleDirtyBadge.hidden = !dirty;
  turtleDirtyBadge.textContent = label;
  regenerateTurtleButton.hidden = !dirty;
}

/**
 * Applies hand-edited TriG. The pane holds the whole document, so the parsed
 * graphs replace the contributions wholesale — a deleted block is a deleted
 * graph. Invalid text changes nothing: an editor is half-typed most of the time.
 */
function handleTurtleChange(text) {
  const { error } = doc.replaceFromTrig(text);
  if (error) {
    showLint(`TriG parse error: ${error.message}`);
    return;
  }
  showLint(null);
  setTurtleDirty(true);
  graphView.setDocument(doc.contributions(), { keepFilters: true });
}

async function handleTextChange(text) {
  // Autosave. This rides the editor's own change debounce and its blur flush, so
  // there is nothing here that has to know about typing rhythm
  // (docs/adr/0023-browser-local-file-store.md).
  const nextStore = setWorkingContent(fileStoreState, text);
  if (nextStore !== fileStoreState) {
    fileStoreState = nextStore;
    saveWorking(fileStoreState);
    renderFiles();
  }

  const parsed = doc.setText(text);
  diagrams = parsed.diagrams;
  const { warnings: modelWarnings } = graphView.setDocument(doc.contributions());
  if (!turtleDirty) await renderTurtle();
  // Linted after the model is built, not before: a location contradiction is a fact
  // about the merged store rather than about any one block, so `buildGraphModel` is
  // the only thing that can see it (docs/adr/0036-location-pins.md).
  showLint([...parsed.warnings, ...modelWarnings]);

  // The pane was left as the user typed it, so say why it no longer matches.
  if (turtleDirty) setTurtleDirty(true, 'edited — mermaid changed since');

  if (!diagrams.some((d) => d.hash === selectedHash)) {
    selectedHash = diagrams[0]?.hash ?? null;
  }
  renderDiagramList(diagramListHost, diagrams, selectedHash, (hash) => {
    selectedHash = hash;
    renderSelectedPreview();
  });
  renderSelectedPreview();
}

function renderSelectedPreview() {
  const selected = diagrams.find((d) => d.hash === selectedHash);
  // The expanded source when the diagram instantiated a template, so the preview
  // draws the instance the graph draws. It is derived, never written back to the
  // document — the editor still shows the one line the user typed.
  const source = selected ? (selected.expandedSource ?? selected.source) : '';
  // Render errors are reported inside the preview pane itself; the header lint
  // chip stays reserved for TriG/parser problems.
  renderMermaidPreview(mermaidHost, source);
}

const defaultExample = examples.find((e) => e.name === '001-layers') ?? examples[0];

// The browser-local library (docs/adr/0023-browser-local-file-store.md). Read
// synchronously, which is why it is localStorage and not IndexedDB: the editor
// is constructed with its text below and fires its first onChange there.
let fileStoreState = loadStore();
onStorageError((reason) => {
  showLint(
    reason === 'quota'
      ? 'Browser storage is full — document changes are no longer being saved.'
      : 'Browser storage is unavailable — document changes are not being saved.',
  );
});
// Nothing stored yet: the example is what the user gets, and it is not their
// unsaved work, so it goes in as a pristine scratch document.
if (!fileStoreState.working.content) {
  fileStoreState = openScratch(fileStoreState, defaultExample.content);
  saveWorking(fileStoreState);
}
const initialText = fileStoreState.working.content;

// Mounted before the mermaid editor, whose createEditorPane() fires its first
// onChange synchronously and expects a TriG pane to write into.
const turtlePane = createTurtlePane(turtleHost, '', handleTurtleChange);
const editorPane = createEditorPane(editorHost, initialText, handleTextChange);
wireCopyButton(copyEditorButton, () => editorPane.getText());
wireCopyButton(copyTurtleButton, () => turtlePane.getText());

/**
 * Applies a fileStore result: `{error}` is reported and changes nothing, so a
 * refusal can never leave the pane showing a library the storage does not hold.
 */
function applyFileResult(result, { structural = true } = {}) {
  if (!result || result.error) {
    if (result?.error) showLint(result.error);
    return null;
  }
  fileStoreState = result.store;
  if (structural) saveStore(fileStoreState);
  else saveWorking(fileStoreState);
  renderFiles();
  return result;
}

function renderFiles() {
  filesDirtyBadge.hidden = !isDirty(fileStoreState);
  renderFilesPane(filesHost, fileStoreState, {
    onOpen: (id) => {
      if (!confirmDiscard()) return;
      const result = applyFileResult(openFile(fileStoreState, id), { structural: false });
      // Not silent: opening a document has to rerun the whole pipeline, so the
      // graph, the TriG pane and the preview follow the editor.
      if (result) editorPane.setText(result.content);
    },
    onSave: (id) => applyFileResult(saveOver(fileStoreState, id, editorPane.getText())),
    onDuplicate: (id) => applyFileResult(duplicateFile(fileStoreState, id)),
    onRename: (id) => {
      const file = fileById(fileStoreState, id);
      const name = window.prompt('Rename to', file?.name ?? '');
      if (name === null) return;
      applyFileResult(renameFile(fileStoreState, id, name));
    },
    onExport: (id) => {
      const file = fileById(fileStoreState, id);
      if (file) downloadText(file.name, file.content);
    },
    onDelete: (id) => {
      const file = fileById(fileStoreState, id);
      if (file && !window.confirm(`Delete ${file.name}? This cannot be undone.`)) return;
      applyFileResult(deleteFile(fileStoreState, id));
    },
  });
}

/**
 * Asks before replacing the working copy with something else. Only work that no
 * file holds is worth a prompt — a document saved, or freshly loaded and
 * untouched, is reproducible.
 */
function confirmDiscard() {
  if (!isDirty(fileStoreState)) return true;
  return window.confirm('The current document has unsaved changes. Discard them?');
}

fileSaveAsButton.addEventListener('click', () => {
  const suggested = uniqueName(fileStoreState, currentFile(fileStoreState)?.name ?? 'document.md');
  const name = window.prompt('Save the current document as', suggested);
  if (name === null) return;
  applyFileResult(saveAs(fileStoreState, name, editorPane.getText()));
});

fileExportButton.addEventListener('click', () => {
  downloadText(currentFile(fileStoreState)?.name ?? 'document.md', editorPane.getText());
});

fileImportButton.addEventListener('click', async () => {
  const picked = await pickTextFile(fileImportInput);
  if (!picked) return;
  if (!confirmDiscard()) return;
  const result = applyFileResult(importFile(fileStoreState, picked.name, picked.text));
  if (result) editorPane.setText(picked.text);
});

// A timer cannot fire during unload, so the last keystrokes would otherwise be
// the ones that are lost — which is exactly what this feature exists to prevent.
window.addEventListener('beforeunload', () => flushStore());

regenerateTurtleButton.addEventListener('click', async () => {
  setTurtleDirty(false);
  showLint(null);
  // The mermaid source is authoritative again, so re-run it: the pane may have
  // deleted graphs that the diagrams still declare.
  await handleTextChange(editorPane.getText());
});

const exampleSelect = document.getElementById('example-select');
for (const example of examples) {
  const option = document.createElement('option');
  option.value = example.name;
  option.textContent = example.fileName;
  if (example.title) option.title = example.title;
  exampleSelect.appendChild(option);
}
// The box starts on the placeholder rather than on the example whose text the
// editor happens to open with: what is being edited may be a restored document,
// and the picker says what it is for, not what is open — the same reason the
// query library box has one.
const examplePlaceholder = document.createElement('option');
examplePlaceholder.value = '';
examplePlaceholder.textContent = 'Pick an example…';
examplePlaceholder.selected = true;
exampleSelect.prepend(examplePlaceholder);
let selectedExample = '';
exampleSelect.addEventListener('change', () => {
  const example = examples.find((e) => e.name === exampleSelect.value);
  if (!example) return;
  // Loading an example replaces the working copy — forking it is what "Save as…"
  // is for — so unsaved work gets a say first.
  if (!confirmDiscard()) {
    exampleSelect.value = selectedExample;
    return;
  }
  selectedExample = example.name;
  applyFileResult({ store: openScratch(fileStoreState, example.content) }, { structural: false });
  editorPane.setText(example.content);
});

// ---------------------------------------------------------------------------
// Window layout (docs/adr/0022-column-tab-groups.md)
// ---------------------------------------------------------------------------

/**
 * Every view the layout can place, declared once.
 *
 * `defaultColumn` is where a first-time user finds it — the TriG pane starts in
 * the right column, beside the graph, because it is a secondary view and the
 * graph should have the width until `Alt+Shift+←` asks otherwise. Where a view
 * sits after that is the user's business: no view has a column of its own.
 *
 * The shortcut lives here rather than in a table of its own, so a view's key is
 * stated in exactly one place and the tab that advertises it cannot disagree.
 * Every view has one, and it only ever reveals that view — moving one between
 * columns is Alt+Shift+←/→ (docs/adr/0022-column-tab-groups.md).
 */
const VIEWS = [
  {
    id: 'editor',
    title: 'Mermaid + D3FEND source',
    shortcut: 'KeyE',
    element: document.getElementById('editor-pane'),
    defaultColumn: 0,
    onShow: () => editorPane.requestMeasure(),
    onMove: ({ hadFocus }) => {
      editorPane.requestMeasure();
      if (hadFocus) editorPane.focus();
    },
  },
  {
    id: 'files',
    title: 'Files',
    shortcut: 'KeyF',
    element: document.getElementById('files-pane'),
    defaultColumn: 0,
    hint: 'Documents stored in this browser — the one you are editing is saved as you type (Alt+F)',
    // Relative timestamps go stale while the pane is hidden.
    onShow: () => renderFiles(),
  },
  {
    id: 'preview',
    title: 'Mermaid preview',
    shortcut: 'KeyM',
    element: document.getElementById('preview-pane'),
    defaultColumn: 2,
  },
  {
    id: 'graph',
    title: 'D3FEND Graph',
    shortcut: 'KeyG',
    element: document.getElementById('graph-pane'),
    defaultColumn: 2,
    defaultActive: true,
    // Cytoscape measured a `display: none` container as zero, and its
    // ResizeObserver only re-measures — framing the drawing is a "you are seeing
    // this for the first time" action, not something a gutter drag should do.
    onShow: () => graphView.fitView(),
    // The info panel used to be closed here as well: re-parenting the ancestor of
    // an open top-layer modal is not well defined. It is an ordinary positioned
    // child of the pane now (docs/adr/0037-non-modal-info-card.md), so it travels
    // with it and stays open.
    onMove: () => graphView.fitView(),
  },
  {
    id: 'trig',
    title: 'TriG (RDF)',
    shortcut: 'KeyR',
    element: document.getElementById('turtle-pane'),
    defaultColumn: 2,
    hint: 'TriG (RDF) — the whole RDF document, and hand-edits drive the graph (Alt+R)',
    onShow: () => turtlePane.requestMeasure(),
    onMove: ({ hadFocus }) => {
      turtlePane.requestMeasure();
      if (hadFocus) turtlePane.focus();
    },
  },
  {
    id: 'query',
    title: 'SPARQL',
    shortcut: 'KeyQ',
    element: document.getElementById('query-pane'),
    defaultColumn: 2,
    hint: 'SPARQL over the document and the loaded knowledge bases (Alt+Q)',
    onShow: () => queryView.requestMeasure(),
    onMove: ({ hadFocus }) => {
      queryView.requestMeasure();
      if (hadFocus) queryView.focus();
    },
  },
];

const dock = createColumnLayout({
  grid: document.getElementById('app-grid'),
  columnEls: ['col-left', 'col-mid', 'col-right'].map((id) => document.getElementById(id)),
  gutterEls: ['gutter-main-col', 'gutter-mid-col'].map((id) => document.getElementById(id)),
  views: VIEWS,
});

renderFiles();

document.getElementById('reset-layout-button').addEventListener('click', () => dock.reset());

// ---------------------------------------------------------------------------
// The session: dump it, or destroy it (docs/adr/0021-sparql-query-pane.md)
// ---------------------------------------------------------------------------

dumpSessionButton.addEventListener('click', () => {
  const now = Date.now();
  downloadText(
    dumpFileName(now),
    buildSessionDump({
      queries: queryView.savedQueries(),
      files: sortedFiles(fileStoreState),
      now,
    }),
  );
});

destroySessionButton.addEventListener('click', () => {
  const queries = queryView.savedQueries().length;
  const files = fileStoreState.files.length;
  if (!queries && !files) {
    showLint('Nothing is saved in this browser.');
    return;
  }
  const confirmed = window.confirm(
    `Delete ${queries} saved ${queries === 1 ? 'query' : 'queries'} and ` +
      `${files} ${files === 1 ? 'document' : 'documents'} from this browser? ` +
      'This cannot be undone — "Dump session" downloads them first.',
  );
  if (!confirmed) return;

  // Cleared synchronously, then reloaded: both stores debounce their writes, and
  // a reload is the only way to be sure no pending timer resurrects what was
  // just destroyed. The layout, the filters and the graph preferences are left
  // alone — those are settings, not the work being cleared.
  clearQueries();
  clearStore(fileStoreState);
  location.reload();
});

// Keyed on `code`, not `key`: with Alt held some layouts report a composed
// character ('µ' for Alt+M) instead of the letter. Derived from the registry so
// a view's key is declared once (see VIEWS above). The keys that act inside a view
// — the graph's bare keys and chips, the SPARQL Sources chip — are that view's own.
const TAB_SHORTCUTS = Object.fromEntries(
  VIEWS.filter((view) => view.shortcut).map((view) => [view.shortcut, view.id]),
);

window.addEventListener(
  'keydown',
  (event) => {
    if (!event.altKey || event.ctrlKey || event.metaKey) return;
    if (event.shiftKey) {
      const delta = { ArrowLeft: -1, ArrowRight: 1 }[event.key];
      if (!delta) return;
      event.preventDefault();
      dock.moveActiveViewBy(delta);
      return;
    }
    const viewId = TAB_SHORTCUTS[event.code];
    if (!viewId) return;
    event.preventDefault();
    dock.revealView(viewId);
    dock.focusTab(viewId);
  },
  true,
);
